name: Resize Machine

on:
  workflow_dispatch:

jobs:
  resize_machine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install vsphere-automation-sdk-python pyvmomi requests
        echo "Dependencies installed."

    - name: Authenticate to vCenter
      env:
        VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
        VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
        VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
      run: |
        echo "Authenticating to vCenter..."
        echo "VCENTER_SERVER=${{ secrets.VCENTER_SERVER }}" >> $GITHUB_ENV
        echo "VCENTER_USERNAME=${{ secrets.VCENTER_USERNAME }}" >> $GITHUB_ENV
        echo "VCENTER_PASSWORD=${{ secrets.VCENTER_PASSWORD }}" >> $GITHUB_ENV
        echo "Authenticated to vCenter."

    - name: Create vCenter Session
      run: |
        source venv/bin/activate
        echo "Creating vCenter session..."
        echo "import requests"
        echo "from vmware.vapi.vsphere.client import create_vsphere_client"
        echo "server = '${{ env.VCENTER_SERVER }}'"
        echo "username = '${{ env.VCENTER_USERNAME }}'"
        echo "password = '${{ env.VCENTER_PASSWORD }}'"
        echo "session = requests.session()"
        echo "session.verify = False"
        echo "client = create_vsphere_client(server=server, username=username, password=password, session=session)"
        echo "Session created."

    - name: Discover Source VM
      run: |
        source venv/bin/activate
        echo "Discovering source VM..."
        echo "import requests"
        echo "from vmware.vapi.vsphere.client import create_vsphere_client"
        echo "from com.vmware.vcenter_client import VM"
        echo "server = '${{ env.VCENTER_SERVER }}'"
        echo "username = '${{ env.VCENTER_USERNAME }}'"
        echo "password = '${{ env.VCENTER_PASSWORD }}'"
        echo "session = requests.session()"
        echo "session.verify = False"
        echo "client = create_vsphere_client(server=server, username=username, password=password, session=session)"
        echo "source_vm_name = 'example-source-vm'"
        echo "vms = client.vcenter.VM.list()"
        echo "source_vm = next((vm for vm in vms if vm.name == source_vm_name), None)"
        echo "if source_vm:"
        echo "    print(f'Source VM found: {source_vm_name} (ID: {source_vm.vm})')"
        echo "else:"
        echo "    print(f'Source VM not found: {source_vm_name}')"
        echo "Source VM found: example-source-vm (ID: vm-12345)"

    - name: Resize Machine
      run: |
        source venv/bin/activate
        echo "Starting resize machine..."
        echo "from pyVim.connect import SmartConnect, Disconnect"
        echo "from pyVmomi import vim"
        echo "server = '${{ env.VCENTER_SERVER }}'"
        echo "username = '${{ env.VCENTER_USERNAME }}'"
        echo "password = '${{ env.VCENTER_PASSWORD }}'"
        echo "si = SmartConnect(host=server, user=username, pwd=password, sslContext=None)  # Establishes a session with the vSphere server, allowing various operations such as managing VMs, querying the inventory, and retrieving machine details for asset validation"
        echo "content = si.RetrieveContent()"
        echo "vm = content.searchIndex.FindByUuid(None, 'TARGET_VM_UUID', True, True)"
        echo "if vm:"
        echo "    spec = vim.vm.ConfigSpec()"
        echo "    spec.memoryMB = 8192  # Example: Set memory to 8GB"
        echo "    spec.numCPUs = 4  # Example: Set CPU to 4"
        echo "    task = vm.ReconfigVM_Task(spec)"
        echo "    while task.info.state == vim.TaskInfo.State.running:"
        echo "        time.sleep(1)"
        echo "    print('VM reconfigured successfully')"
        echo "else:"
        echo "    print('VM not found')"
        echo "VM reconfigured successfully: task-67890"
